apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-fluentd
  labels:
    app: hello-fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-fluentd
  template:
    metadata:
      labels:
        app: hello-fluentd
    spec:
      containers:
      - name: hello-fluentd
        image: hardik794/devops-task:main-1.2.1
        imagePullPolicy: Always
        args: [/bin/sh, -c,
            'i=0; while true; do echo "$i:Hello"; i=$((i+1)); sleep 3; done']
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 10Ki

---
apiVersion: v1
kind: Service
metadata:
  name: "hello-svc-fluentd"
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 30036
  selector:
    app: hello-fluentd

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "hello-hpa-fluentd"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "hello-deployment-fluentd"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 10Ki