apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hardik794/k8s-prc:v2
        imagePullPolicy: Always
        args: [/bin/sh, -c,
            'i=0; while true; do echo "$i:Hello"; i=$((i+1)); sleep 3; done']
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 10Ki

---
apiVersion: v1
kind: Service
metadata:
  name: "hello-svc"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: hello

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "hello-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "hello-deployment"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 10Ki