apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: us.gcr.io/k8s-artifacts-prod/hpa-example
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            # memory: 10Ki
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: "php-svc"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: php

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "php-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "php-deployment"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: 10Ki
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50